### PR TITLE
sync with upstream chart version kube-prometheus-stack-12.10.6

### PR DESCRIPTION
**Pull request by QuentinBisson**
Replace https://github.com/giantswarm/prometheus-operator-app/pull/62

### CODE REVIEW

**Comment by glitchcrab** [comment]
This won't work. CRDs were moved to `/files/` because they are then created by [this](https://github.com/giantswarm/prometheus-operator-app/tree/master/helm/prometheus-operator-app/templates/crd-install) job instead. This means their creation/updates aren't managed by Helm directly, but by the job.

**Comment by glitchcrab** [comment]
I would suggest using a tool like Meld to diff the `crds` and `files` directories, make sure any changes to the CRDs are merged in to the files in `files`, then remove the `crds` directory.

**Comment by ced0ps** [comment]
@QuentinBisson I'm also confused why the PR deletes the `hacks/update-chart.sh` script, which should be used to sync with upstream to make changes persistent over multiple upstream syncs.

**Comment by QuentinBisson** [comment]
I forgot to remove you from the list of reviewers as this PR is currently not in a good state. I tried to use the new script added by @TheoBrigitte to sync the chart but I used it wrongly why resulted in this failing PR. 

@ced0ps  As this script could be replacing the script under `hacks/update-chart.sh` I proposed to remove it in the PR but this should not be done here.

**Comment by ced0ps** [comment]
@QuentinBisson you're absolutely right. I thought this was the pach script but I could swear we removed the old script, when we introduced the pach script. My bad!

**Pull request closed without merging**
