### PR TITLE
Align servicemonitor configuration with current PMO scrape config

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards https://github.com/giantswarm/giantswarm/issues/26221

This PR aligns our current dropped metrics and relabelings to servicemonitors

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Tested this PR in Gauss using this PR as a test.

Rendered Service Monitors:

kube-apiserver

```yaml
k get servicemonitors -n kube-system -oyaml prometheus-operator-app-apiserver
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-operator-app
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-03-22T16:23:45Z"
  generation: 2
  labels:
    app: prometheus-operator-app-apiserver
    app.kubernetes.io/instance: prometheus-operator-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-operator-app
    app.kubernetes.io/version: 45.8.1
    application.giantswarm.io/team: atlas
    chart: prometheus-operator-app-45.8.1
    heritage: Helm
    release: prometheus-operator-app
  name: prometheus-operator-app-apiserver
  namespace: kube-system
  resourceVersion: "1139281043"
  uid: 8deddb75-d16c-4683-8776-1f0c40b7acf3
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    metricRelabelings:
    - action: drop
      regex: apiserver_request_duration_seconds_bucket;(0.15|0.2|0.3|0.35|0.4|0.45|0.6|0.7|0.8|0.9|1.25|1.5|1.75|2|3|3.5|4|4.5|6|7|8|9|15|25|40|50)
      sourceLabels:
      - __name__
      - le
    - action: drop
      regex: rest_client_(rate_limiter_duration_seconds_bucket|request_size_bytes_bucket|response_size_bytes_bucket)
    - action: drop
      regex: apiserver_(longrunning_requests|watch_events_sizes_count|watch_events_sizes_sum|storage_list_fetched_objects_total|storage_list_total|storage_list_returned_objects_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: apiserver_request_(slo_(duration_seconds_bucket|duration_seconds_sum)|duration_seconds_sum)
      sourceLabels:
      - __name__
    - action: drop
      regex: apiserver_response_(sizes_count|sizes_sum)
      sourceLabels:
      - __name__
    - action: drop
      regex: apiextensions_openapi_v2_regeneration_count|apiextensions_openapi_v3_regeneration_count
      sourceLabels:
      - __name__
    port: https
    relabelings:
    - action: replace
      replacement: kubernetes
      targetLabel: app
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: false
      serverName: kubernetes
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
```

coredns

```yaml
k get servicemonitors -n kube-system prometheus-operator-app-coredns -oyaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-operator-app
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-03-30T14:00:44Z"
  generation: 1
  labels:
    app: prometheus-operator-app-coredns
    app.kubernetes.io/instance: prometheus-operator-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-operator-app
    app.kubernetes.io/version: 45.8.1
    application.giantswarm.io/team: atlas
    chart: prometheus-operator-app-45.8.1
    heritage: Helm
    release: prometheus-operator-app
  name: prometheus-operator-app-coredns
  namespace: kube-system
  resourceVersion: "1139281042"
  uid: f1965241-149f-479a-9cf8-1f9327bef553
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    metricRelabelings:
    - action: drop
      regex: coredns_dns_(request_size_bytes_bucket|response_size_bytes_bucket)
      sourceLabels:
      - __name__
    port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-operator-app-coredns
      release: prometheus-operator-app
```

kube-controller-manager

```yaml
k get servicemonitors -n kube-system prometheus-operator-app-kube-controller-manager -oyaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-operator-app
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-03-22T16:23:45Z"
  generation: 2
  labels:
    app: prometheus-operator-app-kube-controller-manager
    app.kubernetes.io/instance: prometheus-operator-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-operator-app
    app.kubernetes.io/version: 45.8.1
    application.giantswarm.io/team: atlas
    chart: prometheus-operator-app-45.8.1
    heritage: Helm
    release: prometheus-operator-app
  name: prometheus-operator-app-kube-controller-manager
  namespace: kube-system
  resourceVersion: "1139269905"
  uid: be275bc4-53d3-4a39-b617-63bd48537ce7
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    metricRelabelings:
    - action: drop
      regex: rest_client_(rate_limiter_duration_seconds_bucket|request_size_bytes_bucket|response_size_bytes_bucket)
    port: http-metrics
    relabelings:
    - action: replace
      replacement: kube-controller-manager
      targetLabel: app
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-operator-app-kube-controller-manager
      release: prometheus-operator-ap
```

kube-etcd
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-operator-app
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-03-30T14:00:44Z"
  generation: 1
  labels:
    app: prometheus-operator-app-kube-etcd
    app.kubernetes.io/instance: prometheus-operator-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-operator-app
    app.kubernetes.io/version: 45.8.1
    application.giantswarm.io/team: atlas
    chart: prometheus-operator-app-45.8.1
    heritage: Helm
    release: prometheus-operator-app
  name: prometheus-operator-app-kube-etcd
  namespace: kube-system
  resourceVersion: "1139281044"
  uid: 5c6bc038-387f-4829-945c-845c700b9c29
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-operator-app-kube-etcd
      release: prometheus-operator-app
```

kube-scheduler
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-operator-app
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-03-22T16:23:45Z"
  generation: 2
  labels:
    app: prometheus-operator-app-kube-scheduler
    app.kubernetes.io/instance: prometheus-operator-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-operator-app
    app.kubernetes.io/version: 45.8.1
    application.giantswarm.io/team: atlas
    chart: prometheus-operator-app-45.8.1
    heritage: Helm
    release: prometheus-operator-app
  name: prometheus-operator-app-kube-scheduler
  namespace: kube-system
  resourceVersion: "1139269906"
  uid: 23402479-1c6b-4789-bf07-f027060661cd
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    metricRelabelings:
    - action: drop
      regex: rest_client_(rate_limiter_duration_seconds_bucket|request_size_bytes_bucket|response_size_bytes_bucket)
    port: http-metrics
    relabelings:
    - action: replace
      replacement: kube-scheduler
      targetLabel: app
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-operator-app-kube-scheduler
      release: prometheus-operator-app
```

kubelet / cAdvisor appears to be 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-operator-app
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-03-30T14:00:44Z"
  generation: 3
  labels:
    app: prometheus-operator-app-kubelet
    app.kubernetes.io/instance: prometheus-operator-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-operator-app
    app.kubernetes.io/version: 45.8.1
    application.giantswarm.io/team: atlas
    chart: prometheus-operator-app-45.8.1
    heritage: Helm
    release: prometheus-operator-app
  name: prometheus-operator-app-kubelet
  namespace: kube-system
  resourceVersion: "1139338616"
  uid: e1aae4a8-c2c3-4ac3-868f-1b880d594f8f
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    metricRelabelings:
    - action: drop
      regex: rest_client_(rate_limiter_duration_seconds_bucket|request_size_bytes_bucket|response_size_bytes_bucket)
    - action: labeldrop
      regex: uid
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    metricRelabelings:
    - action: drop
      regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_memory_(mapped_file|swap)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_(file_descriptors|tasks_state|threads_max)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_spec.*
      sourceLabels:
      - __name__
    - action: drop
      regex: .+;
      sourceLabels:
      - id
      - pod
    - action: labeldrop
      regex: id|name
    - action: drop
      regex: container_(blkio_device_usage_total|network_transmit_errors_total|network_receive_errors_total|memory_failures_total|memory_max_usage_bytes|memory_failcnt)
    path: /metrics/cadvisor
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    path: /metrics/probes
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
```

**Comment by QuentinBisson** [comment]
image
Targets are getting scraped by the agent on Gauss MC

**Comment by QuentinBisson** [comment]
Memory usage on Gauss MC:
image

**Comment by QuentinBisson** [comment]
It spiked a bit with Out of order samples on a 50 node clusters but it's overall fine (2.5G)

image

**Comment by QuentinBisson** [comment]
The spike at 9:50 is when I enabled KSM:
image


Sadly, we do not really have containers running on the nodes so it's not representative but the real usage does not appear to be that high on our clusters.

**Comment by QuentinBisson** [comment]
Letting the WAL fill out for an hour or so and then let's see

**Comment by QuentinBisson** [comment]
Remote write seems fine 
image

**Comment by QuentinBisson** [comment]
Wal with KSM after 2 hours:
image

**Comment by QuentinBisson** [comment]
On a bigger timeframe, this actually does not rise that much over time 
image

**Review by marieroque — APPROVED** [review]
Go 🚀

**Pull request merged**
