### PR TITLE
Label prometheus-operator deployment with atlas as monitoring team

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/22290

Add `application.giantswarm.io/team: atlas` label on deployment.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
The label is used by the app-exporter actually https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/routing_app_alerts/

I'm wondering if we could not use this to create a team label on the scrape targets so we could relabel it to a label called team and use this label instead of adding a new one.

@giantswarm/team-honeybadger is the `application.giantswarm.io/team` label added to the templatize helm charts ? Would it be possible to do so automagically to help with the routing of alerts ?

**Comment by MarcelMue** [comment]
I am not aware of it being used inside the helm chart as a standard. Maybe @piontec knows?

**Comment by piontec** [comment]
Uhm.. I'm not sure what you mean. The label has to be added by chart devs, like here: https://github.com/giantswarm/flux-app/blob/2167424080feae2983117cdb5982bcac9de8e6e6/helm/flux-app/Chart.yaml#L4
What do you want to replace it with? And how do you want to automate it?

**Comment by QuentinBisson** [comment]
The idea would not be to replace it with but to templetize it as label on the kubernetes manifests. Can we do that easily ?

**Comment by TheoBrigitte** [comment]
Updated this PR to use the already existing `application.giantswarm.io/team` label.

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
