### PR TITLE
split CRD into separate chart

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: giantswarm/giantswarm#20256

* split the crd and crd-install job into `prometheus-operator-crd` chart
* added crd-uninstall job which remove the installed crds
* removed the `if .Values.crds.install` as this will be part of dependency condition in later PR
* updated helm.sh annotations
* only push `prometheus-operator-crd` on `v*-crd` tags

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
Noice,  Should we propose that upstream though ?

**Comment by TheoBrigitte** [comment]
Sorry I should have created this PR as draft, its not ready yet. Will ask for review later

**Comment by TheoBrigitte** [comment]
crd-chart installation works

```
$ helm install prometheus-operator-crd ./prometheus-operator-crd-0.12.1-e9a2e13b7888b404a6d9cbf64c197de4b8b101f4.tgz
W0106 15:57:20.681659  143265 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0106 15:57:21.657563  143265 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0106 15:57:43.874823  143265 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME: prometheus-operator-crd
LAST DEPLOYED: Thu Jan  6 15:57:17 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
prometheus-operator-crd has been installed. Check its status by running:
  kubectl api-resources --api-group=monitoring.coreos.com
```

**Comment by TheoBrigitte** [comment]
NOTE: how to solve the internal dependency from prometheus-operator-app to prometheus-operator-crd now?

1. could release a `v0.12.1-crd` release

**Review by QuentinBisson — APPROVED** [review]
LGTM

**Pull request merged**
