### PR TITLE
Add direct metric renames for coredns 1.7.0

### PR DESCRIPTION
**Pull request by stone-z**
Towards https://github.com/giantswarm/giantswarm/issues/15601

### CODE REVIEW

**Comment by stone-z** [comment]
@giantswarm/app-squad-prometheus there is one more metric which has to change:
`coredns_dns_request_type_count_total` is now part of `coredns_dns_requests_total`. The old name is used [here](https://github.com/giantswarm/prometheus-operator-app/blob/93364024065287cd38cbd3ead5f9f63d081ca28b/helm/prometheus-operator-app/templates/grafana/dashboards-1.14/k8s-coredns.yaml#L188) -- do you have a preference how to support both old + new names?

**Comment by ubergesundheit** [comment]
> do you have a preference

no preference from my side

ping @webwurst

**Review by ubergesundheit — APPROVED** [review]

**Comment by stone-z** [comment]
Followup - how do I actually test this thing?

**Comment by cokiengchiara** [comment]
For testing, does this help? https://intranet.giantswarm.io/docs/organizational-structure/teams/halo/app-release-checklist/

**Comment by puja108** [comment]
@alex-dabija @cornelius-keller can you check if you might need to take this over, this was finished, but blocked cause we didn't know how to test it, not even sure it's still needed.

**Comment by TheoBrigitte** [comment]
@stone-z what do we do with this PR ?

**Comment by stone-z** [comment]
Years later and nobody has missed this. The current DNS dashboard seems to have no relation to this file anyway, I don't know if/when we even show this dashboard. I'm closing it

**Pull request closed without merging**
