### PR TITLE
Upgrade to v0.50.0

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: giantswarm/giantswarm#19727

This PR does the following:
- Upgrade `prometheus-operator` to `v0.50.0` (kube-prometheus-stack-19.3.0)
- fix `.Values.grafana.sidecar.dashboards.multicluster`
- remove `values.schema.json`
- fix docker image repositories
- remove `kube-webhook-certgen` image sha

/!\ Reminder: do not merge via github.

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
Need to find a way to get `k8s.gcr.io/ingress-nginx/kube-webhook-certgen` working but also not override previous `jettech/kube-webhook-certgen` image, see https://github.com/giantswarm/retagger/pull/655

**Comment by TheoBrigitte** [comment]
Removing docker image sha since this is beyond my comprehension

<details>
  <summary>docker digest madness</summary>

### Working example with `alertmanager`

We do retag `quay.io/prometheus/alertmanager` into `giantswarm/alertmanager` and push it to our 3 registries (docker hub, quay, and aliyun)

The upstream image is multi-arch manifest 
```
$ docker buildx imagetools inspect quay.io/prometheus/alertmanager:v0.22.2
Name:      quay.io/prometheus/alertmanager:v0.22.2
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:624c1a5063c7c80635081a504c3e1b020d89809651978eb5d0b652a394f3022d

Manifests:
  Name:      quay.io/prometheus/alertmanager:v0.22.2@sha256:6ff24033b35ff1f6f66e2fc8fa4792cf91f0fee8da57955051036dbb8b6a6d44
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      quay.io/prometheus/alertmanager:v0.22.2@sha256:e5e4a558ec92574963b98e14108d6c72b481aab755fcaf5385d3ea660066278d
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64

  Name:      quay.io/prometheus/alertmanager:v0.22.2@sha256:25c93642300f8319606024c2ccdfa85eb857bfb98a3a00d641f1ceb221097dec
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm

  Name:      quay.io/prometheus/alertmanager:v0.22.2@sha256:6b3546ed62149ae144ad05fc3ffeba0903b2403782bc5ba284b5e853c6e8ea9c
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/ppc64le

  Name:      quay.io/prometheus/alertmanager:v0.22.2@sha256:2eb2e85d6dc0a8a9e744db0aec1e0acc0e2a60cbf5b203f4bdfb13b885009f4b
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/s390x
```

While retagging nothing changes in the image and we get the upstream digest (`sha256:6ff24033b35ff1f6f66e2fc8fa4792cf91f0fee8da57955051036dbb8b6a6d44`) from `Platform:  linux/amd64`

```
$ docker pull quay.io/giantswarm/alertmanager:v0.22.2
v0.22.2: Pulling from giantswarm/alertmanager
Digest: sha256:6ff24033b35ff1f6f66e2fc8fa4792cf91f0fee8da57955051036dbb8b6a6d44
Status: Downloaded newer image for quay.io/giantswarm/alertmanager:v0.22.2
quay.io/giantswarm/alertmanager:v0.22.2

$ docker pull giantswarm/alertmanager:v0.22.2
v0.22.2: Pulling from giantswarm/alertmanager
Digest: sha256:6ff24033b35ff1f6f66e2fc8fa4792cf91f0fee8da57955051036dbb8b6a6d44
Status: Downloaded newer image for giantswarm/alertmanager:v0.22.2
docker.io/giantswarm/alertmanager:v0.22.2

$ docker pull registry-intl.cn-shanghai.aliyuncs.com/giantswarm/alertmanager:v0.22.2
v0.22.2: Pulling from giantswarm/alertmanager
Digest: sha256:6ff24033b35ff1f6f66e2fc8fa4792cf91f0fee8da57955051036dbb8b6a6d44
Status: Downloaded newer image for registry-intl.cn-shanghai.aliyuncs.com/giantswarm/alertmanager:v0.22.2
registry-intl.cn-shanghai.aliyuncs.com/giantswarm/alertmanager:v0.22.2
```

### Non-working example with `kube-webhook-certgen`

We do retag `k8s.gcr.io/ingress-nginx/kube-webhook-certgen` into `giantswarm/kube-webhook-certgen` and push it to our 3 registries (docker hub, quay, and aliyun)

The upstream image is multi-arch manifest 
```
$ docker buildx imagetools inspect k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
Name:      k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:f3b6b39a6062328c095337b4cadcefd1612348fdd5190b1dcbcb9b9e90bd8068

Manifests:
  Name:      k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0@sha256:875a90ff79245201757faa1c3b9e4cecdb81a6e1436008b0462a236d5241288f
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0@sha256:82670eb425cedd7b3e6e3523f95e624fc9830e7048da31dafe67260a9d51822f
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm/v7

  Name:      k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0@sha256:6b91d0434942504defa54cd50b15cddda0df58b4cc99cf5ec365762f295306ea
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64

  Name:      k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0@sha256:a225978590c210043d56ad2e30db1f8950b9b7e10790bf4c9a5b89928a134526
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/s390x
```
While retagging nothing changes in the image BUT we get the unknown digest (`sha256:a0f92f5f828e9bf8e3a4c672080067e0079e95f9af8583059eab0c11f4dc7cfe`) from ... _god knows where_.

```
$ docker pull quay.io/giantswarm/kube-webhook-certgen:v1.0
v1.0: Pulling from giantswarm/kube-webhook-certgen
Digest: sha256:a0f92f5f828e9bf8e3a4c672080067e0079e95f9af8583059eab0c11f4dc7cfe
Status: Downloaded newer image for quay.io/giantswarm/kube-webhook-certgen:v1.0
quay.io/giantswarm/kube-webhook-certgen:v1.0
```
</details>

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Can you share how you upgraded so I can release 0.52.1 ?

**Comment by TheoBrigitte** [comment]
> Can you share how you upgraded so I can release 0.52.1 ?

I've done it via `git subtree` using the same procedure as for dependencies in PMO, see https://github.com/giantswarm/prometheus-meta-operator#upgrade. Let's pair next time so you learn the git subtree magic too.

**Pull request merged**
