### PR TITLE
Remove chart suffix

### PR DESCRIPTION
**Pull request by omegas27**
To merge after https://github.com/giantswarm/prometheus-operator-app/pull/22

Will create release 0.3.0 after this is one is merged

### CODE REVIEW

**Comment by sslavic** [comment]
@omegas27 @oponder @cokiengchiara with rename (removal of chart suffix), now we have two prometheus-operator apps listed in Giant Swarm catalog, see screenshot from gorgoth CP

screenshot-happa g8s gorgoth gridscale kvm gigantic io-2020 06 16-08_33_17

Hope you agree, we should cleanup old app with "-chart" suffix and keep one without the suffix.
Do you know of a way to find if the app variant with "-chart" suffix is being used by anyone?

**Comment by omegas27** [comment]
I agree we should clean it up. I think the only way would be to list all the apps/charts in installations/ Maybe @giantswarm/team-batman-engineers have an idea on how to discover installed apps? Or maybe we need to create an issue for them

**Comment by sslavic** [comment]
@giantswarm/sig-data is there a dashboard we can use to check if an app/version is used anywhere?

**Comment by rossf7** [comment]
There is this Managed Apps dashboard. https://giantswarm.grafana.net/d/5hNfH3qZz/managed-apps

It says there are 3 instances running and all on Azure. I think you could filter more by customer to find the installations. Not sure if there is a better way to find that.

Screen Shot 2020-06-16 at 9 39 01 AM

**Comment by sslavic** [comment]
Checked, it seems prometheus-operator-app-chart was used on gk-software's goku CP TCs only.

https://gigantic.slack.com/archives/CRZN9GLJW/p1592382839100300?thread_ts=1592303934.094900&cid=CRZN9GLJW

@T-Kukawka fixed/migrated one existing usage. Customer still has to update their auto deployed infra code and confirm if new version works for them. Once confirmed, we can manually cleanup variant with the chart suffix so there is no noise of two variants displayed in catalogs in happa.

**Comment by sslavic** [comment]
@T-Kukawka @giantswarm/team-batman-engineers  there was prometheus App CR for goku / 2db3k on goku CP, it had deletion timestamp, but it couldn't be deleted - App CR was allowed to be submitted with lots of validation problems and simply wrong data (case problem in `kubeConfig.secret.name`, and wrong `catalog`). Since app-operator assumes App CR is valid it was stuck in handling the deletion request. I've fixed those and app got deleted. Likely customer submitted them via API, through some automation. To prevent this validation (schema, webhook, ...) needs to be put in place, and customer needs to update/fix infra code.

Some of the validation issues:
- missing label `app-operator.giantswarm.io/version: 1.0.0`
- instead of
```
  catalog: helm-stable
  config:
    configMap:
      name: 2db3k-cluster-values
      namespace: 2db3k
    inCluster: false
    kubeConfig:
      name: 2db3k
    secret:
      name: 2db3k-kubeConfig
      namespace: 2db3k
  name: prometheus-operator-app-chart
  namespace: prometheus
  userConfig:
    configMap:
      name: promethues-user-values
      namespace: 2db3k
    secret:
      name: ""
      namespace: ""
```
replaced with:
```
  catalog: giantswarm
  config:
    configMap:
      name: 2db3k-cluster-values
      namespace: 2db3k
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: 2db3k
    inCluster: false
    secret:
      name: 2db3k-kubeconfig
      namespace: 2db3k
  name: prometheus-operator-app-chart
  namespace: prometheus
  userConfig:
    configMap:
      name: promethues-user-values
      namespace: 2db3k
    secret:
      name: ""
      namespace: ""
```

I will cleanup prometheus-operator-app-chart from the giantswarm catalog, only variant without `-chart` suffix will remain and should be used from now on.

**Comment by rossf7** [comment]
> App CR was allowed to be submitted with lots of validation problems and simply wrong data (case problem in kubeConfig.secret.name, and wrong catalog). 

Thanks @sslavic this is hitting us hard at the moment. I think the solution is to have an admission controller for app CRs.

First step is validating to make sure the CMs and secrets exist. But the real fix is defaulting. This is all that should be required. I'm going to work on it this week during hackathon.  

```yaml
  catalog: giantswarm
  name: prometheus-operator-app-chart
  namespace: prometheus
  userConfig:
    configMap:
      name: prometheus-user-values
      namespace: 2db3k
```

**Pull request merged**
