### PR TITLE
Fix CRD install problems

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/15240

We can't use the crd-install job exactly the same as we do elsewhere because this
chart also contains CRs which use the CRDs, and helm doesn't know they're CRDs
when they're in a different directory to `/crds/`.

Using this method causes the following to happen.

- on a fresh install of the chart
   - Helm creates the CRDs using its native method
   - crd-install job then also applies them, but this does nothing as they don't
change
   - the rest of the chart deploys successfully
- on an upgrade:
   - Helm doesn't do anything with CRDs directly
   - crd-install job applies any changes

### CODE REVIEW

**Comment by glitchcrab** [comment]
just fyi @TheoBrigitte

**Comment by glitchcrab** [comment]
tested on a local kind cluster with the default values.yaml:

```
[shw ~](☸ kind-kind:prom-operator)$ kg po
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prom-operator-prometheus-o-alertmanager-0   2/2     Running   0          25m
prom-operator-prometheus-o-operator-59dbc59c7d-7wlnm     1/1     Running   0          25m
prometheus-prom-operator-prometheus-o-prometheus-0       2/2     Running   1          25m
[shw ~](☸ kind-kind:prom-operator)$ kg crd
NAME                                        CREATED AT
alertmanagerconfigs.monitoring.coreos.com   2021-01-19T16:46:33Z
alertmanagers.monitoring.coreos.com         2021-01-19T16:46:33Z
podmonitors.monitoring.coreos.com           2021-01-19T16:46:33Z
probes.monitoring.coreos.com                2021-01-19T16:46:33Z
prometheuses.monitoring.coreos.com          2021-01-19T16:46:33Z
prometheusrules.monitoring.coreos.com       2021-01-19T16:46:33Z
servicemonitors.monitoring.coreos.com       2021-01-19T16:46:33Z
```

**Comment by glitchcrab** [comment]
logs from the crd-install pod on first install:

```
+ prometheus-operator-app-crd-install-cv2kx › kubectl
prometheus-operator-app-crd-install-cv2kx kubectl + set -o nounset
prometheus-operator-app-crd-install-cv2kx kubectl + kubectl apply -f /data/
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/alertmanagerconfigs.monitoring.coreos.com configured
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com configured
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com configured
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com configured
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com configured
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com configured
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com configured
prometheus-operator-app-crd-install-cv2kx kubectl Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus-operator-app-crd-install-cv2kx kubectl customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com configured
- prometheus-operator-app-crd-install-cv2kx › kubectl
- ```

**Comment by yasn77** [comment]
@glitchcrab You might be interested in this https://github.com/giantswarm/giantswarm/issues/13746

I am working on it now, albeit rather slowly since I am n00b gopher. But once it's in place, it will mean that CRDs can be managed out of bounds and when installing the chart, stuff in the cards folder will be ignored.

**Comment by glitchcrab** [comment]
> @glitchcrab You might be interested in this [giantswarm/giantswarm#13746](https://github.com/giantswarm/giantswarm/issues/13746)
> 
> I am working on it now, albeit rather slowly since I am n00b gopher. But once it's in place, it will mean that CRDs can be managed out of bounds and when installing the chart, stuff in the cards folder will be ignored.

This is interesting! I had thought that another way out of this mess would be to install the CRDs as a separate chart and this would make that a lot cleaner.

**Review by webwurst — APPROVED** [review]
Looks nice! And good to me if it works for you

**Review by piontec — APPROVED** [review]
LGTMIIWFY

**Review by ced0ps — APPROVED** [review]
Deployed it on a GS workload cluster I had open for testing jaeger deployment. Works perfectly on first install :+1:

**Review by TheoBrigitte — APPROVED** [review]
Brilliant!

Sorry I hadn't tested this case of deploying prometheus-operator to a fresh cluster this should also fix the case where someone try to deploy it with all its CRs enabled.
Great job.

**Pull request merged**
