### PR TITLE
Remove uid (pod_id) from drop labels in KSM metrics

### PR DESCRIPTION
**Pull request by marieroque**
towards https://github.com/giantswarm/giantswarm/issues/27181

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Where does the doc say we need to keep it? We removed it because it is a high cardinility label :(

**Comment by marieroque** [comment]
> doc say we need to keep it? We removed it because it is a high cardinility

If you read this doc https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md
For instance the metric `kube_pod_status_phase` which is currently sometimes in duplicate samples, you see `uid=<pod-uid>` and if we remove this label when a pod is restarting, I guess it causes duplicate samples because we have no more discriminent.

**Comment by QuentinBisson** [comment]
This makes me quite unhappy

**Review by QuentinBisson — APPROVED** [review]

**Comment by marieroque** [comment]
Yes me too :-(
But I think we can drop some metrics rather than act on label (which is dangerous).

For instance, I'm not sure we need to keep metrics like `kube_XXX_annotations` and there are a lot.

I'm opening another PM to tune KSM servicemonitor...

**Pull request merged**
